#!/system/bin/sh

# ===========================================================================
#  Virtuous ROM Tools (rmk, chrisch)
#
#  $LastChangedDate: 2011-07-18 10:39:15 +0200 (lun. 18 juil. 2011) $
# ===========================================================================

. /system/virtuous/scripts/virtuous-functions.sh

CARRIER=`$GETPROP ro.carrier`

if [ "$CARRIER" = "TMUS" ] ; then
    $SYSBIN_DIR/insmod $SYSLIB_DIR/modules/kineto_gan.ko
fi
