#!/system/bin/sh
#ThunderBolt!
# ==============================================================
# ==============================================================
# ==============================================================
# Optimize SQlite databases of apps
# ==============================================================
# ==============================================================
# ==============================================================
# ==============================================================

echo "";
echo "*********************************************";
echo "Optimizing and defragging your database files (*.db)";
echo "Ignore the 'database disk image is malformed' error";
echo "Ignore the 'no such collation sequence' error";
echo "*********************************************";
echo "";

for i in \
`busybox find /data -iname "*.db"`; 
do \
	sqlite3 $i 'VACUUM;';
	sqlite3 $i 'REINDEX;';
done;

if [ -d "/dbdata" ]; then
	for i in \
	`busybox find /dbdata -iname "*.db"`; 
	do \
		sqlite3 $i 'VACUUM;';
		sqlite3 $i 'REINDEX;';
	done;
fi;


if [ -d "/datadata" ]; then
	for i in \
	`busybox find /datadata -iname "*.db"`; 
	do \
		sqlite3 $i 'VACUUM;';
		sqlite3 $i 'REINDEX;';
	done;
fi;


for i in \
`busybox find /sdcard -iname "*.db"`; 
do \
	sqlite3 $i 'VACUUM;';
	sqlite3 $i 'REINDEX;';
done;
