#!/sbin/sh

# ===========================================================================
#  Virtuous ROM Tools (rmk)
#
#  $LastChangedDate: 2012-06-20 11:05:42 +0200 (Wed, 20 Jun 2012) $
# ===========================================================================

. /system/virtuous/scripts/virtuous-functions.sh

PATH=/sbin
export PATH

# Unmount all filesystems
umount /data
umount /cache
umount /devlog

# Convert from ext3 to ext4

# /data
tune2fs -O extents,uninit_bg,dir_index /dev/block/mmcblk0p26
e2fsck -p /dev/block/mmcblk0p26
tune2fs -o journal_data_writeback /dev/block/mmcblk0p26

# /cache
tune2fs -O extents,uninit_bg,dir_index /dev/block/mmcblk0p27
e2fsck -p /dev/block/mmcblk0p27
tune2fs -o journal_data_writeback /dev/block/mmcblk0p27

# /devlog
tune2fs -O extents,uninit_bg,dir_index /dev/block/mmcblk0p28
e2fsck -p /dev/block/mmcblk0p28
tune2fs -o journal_data_writeback /dev/block/mmcblk0p28
