#!/sbin/sh

# ===========================================================================
#  Virtuous ROM Tools (rmk, chrisch)
#
#  $LastChangedDate: 2011-07-17 06:14:31 +0200 (dim. 17 juil. 2011) $
# ===========================================================================

# Install busybox.

cd /system/xbin
/system/bin/chmod 755 busybox
./busybox --install -s /system/xbin

. /system/virtuous/scripts/virtuous-functions.sh

# Setup environment.

DATAMOUNTED=0
DATADATAMOUNTED=0

if $TEST $( $GREP -c " /data " "/proc/mounts" ) -eq 0; then
  $MOUNT /data
  DATAMOUNTED=1
fi

if $TEST $( $GREP -c " /datadata " "/proc/mounts" ) -eq 0; then
  $MOUNT /datadata
  DATADATAMOUNTED=1
fi

$TOUCH $PACKAGESXML
$CHOWN 1000.1000 $PACKAGESXML
$CHMOD 664 $PACKAGESXML

# Prepare data directories if the user wiped.

create_state_dirs

for DISABLED_APP in $($LS $VIRTUOUS_STATE_DIR/disabled/*.apk) ; do
  APPNAME=$($BASENAME $DISABLED_APP)

  $MV $SYSAPP_DIR/$APPNAME $VIRTUOUS_ROOT_DIR/app.disabled
done

# Remove T-Mobile specific options unless the carrier is in fact
# T-Mobile.  This includes Swype (US only) and wifi calling.

CARRIER=`$GETPROP ro.carrier`

if [ ! "$CARRIER" = "TMUS" ] ; then
    $RM -f $SYSAPP_DIR/com.android.kineto.apk
    $RM -f $SYSLIB_DIR/libkineto.so
    $RM -f $SYSLIB_DIR/librilswitch.so
    $RM -f $SYSLIB_DIR/libganril.so
    $LN -s $SYSLIB_DIR/libhtc_ril.so $SYSLIB_DIR/librilswitch.so
fi

# Cleanup ROM-controlled sdcard directories.

$MOUNT $SDCARD_DIR
$RM -rf $VIRTUOUS_ROMAPP_DIR
$RM -rf $VIRTUOUS_EBOOK_DIR
$MKDIR -p $VIRTUOUS_USERAPP_DIR

# After a fresh ROM install, remove the installed state such that the
# init script is triggered on startup.

if $TEST -f $VIRTUOUS_INSTALLED; then
  $RM $VIRTUOUS_INSTALLED
fi

if $TEST $DATAMOUNTED -eq 1; then
  $UMOUNT /data
fi

if $TEST $DATADATAMOUNTED -eq 1; then
  $UMOUNT /datadata
fi
